[package]
name = "bec_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
fftw = "0.8.0"
lapack = "0.20.0"
plotters = "0.3.3"