name: BEC Test

on:
  push:
    branches: [ test ]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/rust-ci-base:latest
      options: --user root   # 👈 run as root so apt works

    env:
      PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
      PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1

    steps:
      - uses: actions/checkout@v3

      - name: Ensure git is available
        run: |
          apt-get update
          apt-get install -y git

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: |
          mkdir -p target/nextest/ci
          export RUSTFLAGS="-C link-args=-lopenblas"
          export RUSTFLAGS="$RUSTFLAGS -C link-args=-lpthread"
          export RUSTFLAGS="$RUSTFLAGS -C link-args=-lm"
          cargo nextest run --profile ci

      - name: Upload test results
        uses: dorny/test-reporter@v1
        with:
          name: Rust Nextest
          path: target/nextest/ci/junit.xml
          reporter: java-junit
          fail-on-error: true
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-empty: true
