name: Rust with LAPACK

on:
  push:
    branches: [test]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 🧰 Install dependencies
      - name: Install system BLAS/LAPACK
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev liblapack-dev gfortran fontconfig libfontconfig1-dev pkg-config

      # 🧠 Configure Rust to link against system libraries
      - name: Configure environment
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "RUSTFLAGS=-C link-args=-lopenblas -llapack -lblas -lgfortran" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "RUSTFLAGS=-C link-args=-lopenblas -llapack -lblas" >> $GITHUB_ENV
          else
            echo "RUSTFLAGS=-C link-args=-lopenblas" >> $GITHUB_ENV
          fi

      # 🦀 Build & test
      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
