name: Rust CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
      PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1
        RUSTFLAGS: -C link-args=-lopenblas -C link-args=-lpthread -C link-args=-lm
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenblas-dev \
            liblapack-dev \
            gfortran \
            fontconfig \
            libfontconfig1-dev \
            pkg-config

      - name: Set linker flags for Rust
        run: |
          echo "RUSTFLAGS=-L $OPENBLAS_DIR -C link-args='-lopenblas -lpthread -lm'" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: cargo test --release
