name: Test

on:
  push:
    branches: [ "master", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install LAPACK/FFTW
      run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev liblapacke-dev libfftw3-dev libfontconfig1-dev gfortran
    - name: Install cargo-nextest
      run: |
          cargo install cargo-nextest --locked --force
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Set library environment variables
      run: |
          echo "OPENBLAS_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "LAPACK_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "FFTW_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
    - name: Run tests
      run: cargo run nextest
          

