name: Rust CI Test

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
      PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenblas-dev \
            liblapack-dev \
            gfortran \
            fontconfig \
            libfontconfig1-dev \
            pkg-config

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Nextest
        run: cargo install --locked cargo-nextest

      - name: Run tests
        run: |
          export RUSTFLAGS="-C link-args=-lopenblas"
          export RUSTFLAGS="$RUSTFLAGS -C link-args=-lpthread"
          export RUSTFLAGS="$RUSTFLAGS -C link-args=-lm"
          cargo nextest run --profile ci

      - name: Upload test results
        uses: dorny/test-reporter@v1
        with:
          name: Rust Nextest
          path: target/nextest/ci/junit.xml
          reporter: github
          fail-on-error: true
