name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install LAPACK/FFTW
      run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev liblapack-dev libfftw3-dev
