name: Test

on:
  push:
    branches: [ "master", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install LAPACK/FFTW
      run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev liblapack-dev libfftw3-dev libfontconfig1-dev build-essential gfortran
    - name: Install cargo-nextest
      run: |
          cargo install cargo-nextest --locked --force
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Set library environment variables
      run: |
          echo "export LAPACK_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "export LAPACK_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "export BLAS_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "export OPENBLAS_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "export RUSTFLAGS='-C link-args=-lopenblas'" >> $GITHUB_ENV
          echo "FFTW_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
    - name: Run tests
      run: cargo build --verbose
          

