name: BEC Test

on:
  push:
    branches: [ test ]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/rust-ci-base:latest

    outputs:
      junit-path: target/nextest/ci/junit.xml

    env:
      PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
      PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: |
          mkdir -p target/nextest/ci
          export RUSTFLAGS="-C link-args=-lopenblas"
          export RUSTFLAGS="$RUSTFLAGS -C link-args=-lpthread"
          export RUSTFLAGS="$RUSTFLAGS -C link-args=-lm"
          cargo nextest run --reporter junit --output-path target/nextest/ci/junit.xml --profile ci

      - name: Upload artifact for host reporter
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/nextest/ci/junit.xml

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: junit-results
          path: target/nextest/ci

      - name: Upload test results to GitHub
        uses: dorny/test-reporter@v1
        with:
          name: Rust Nextest
          path: target/nextest/ci/junit.xml
          reporter: java-junit
          fail-on-error: true
