name: Rust CI

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up Rust
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      # 3️⃣ Install system dependencies for LAPACK and FFTW
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev liblapack-dev libfftw3-dev

      # 4️⃣ Install cargo-nextest
      - name: Install cargo-nextest
        run: |
          cargo install cargo-nextest --locked --force
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          cargo nextest --version

      # 5️⃣ Optional: set environment variables if crates require them
      - name: Set library environment variables
        run: |
          echo "OPENBLAS_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "LAPACK_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "FFTW_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      # 6️⃣ Run tests with cargo-nextest
      - name: Run tests
        run: cargo nextest run --workspace --profile ci
