name: Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    name: Run Rust tests with nextest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked

      - name: Run tests (JUnit report)
        run: |
          cargo nextest run --profile ci 

      - name: Upload JUnit report to GitHub
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: nextest.xml
          check_name: "Test Results"
          fail_on_failure: true

